file_handle = open('text.txt', 'r')
print('way 1: line by line')
for line in file_handle:
    print(line.strip())
file_handle.close()
print('-------------------------')
file_handle = open('text.txt', 'r')
print('way 2: read the whole file')
text = file_handle.read()
print(text)
file_handle.close()
print('-------------------------')
print(text)
small_text = text.lower()
print('-------------------------')
print(small_text)
outfile = open('small.text', 'w')
outfile.write(small_text)
outfile.close()
# a = append
outfile = open('small.text', 'a')
outfile.write('\nbon appetite')
outfile.close()
